# Generated by Django 4.2.30 on 2026-08-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15, unique=True)),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchantInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_key', models.CharField(max_length=100, unique=True)),
                ('merchant_salt', models.CharField(max_length=100, unique=True)),
                ('merchant_name', models.CharField(max_length=100)),
                ('merchant_email', models.EmailField(max_length=254)),
                ('merchant_phone', models.CharField(max_length=15)),
                ('merchant_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchant_order_id', models.CharField(max_length=100)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_currency', models.CharField(default='INR', max_length=10)),
                ('order_status', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.customerinfo')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.merchantinfo')),
            ],
        ),
    ]
