# Generated by Django 4.2.30 on 2026-08-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='merchant_id',
            new_name='merchant',
        ),
    ]
