# Generated by Django 4.2.30 on 2026-08-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_merchant_id_orderinfo_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pa_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
