# Generated by Django 4.2.30 on 2026-08-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_orderinfo_pa_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
