# Generated by Django 4.2.30 on 2026-08-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
        ('payments', '0004_orderinfo_pa_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='shipment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.shipment'),
        ),
    ]
