# Generated by Django 4.2.30 on 2026-08-10 08:55

from django.db import migrations, models
import django.utils.timezone
import tracking.models.trackinginfo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(default=tracking.models.trackinginfo.gen_awb, max_length=64, unique=True)),
                ('courier', models.CharField(blank=True, max_length=128, null=True)),
                ('pa_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('invoice', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('HELD', 'Held'), ('RELEASED', 'Released'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered'), ('REFUNDED', 'Refunded'), ('SETTLED', 'Settled')], default='CREATED', max_length=32)),
                ('history', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
